#!/usr/bin/bash

python train_test/Load/load_qr_gefcom2014.py 4 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 4 "gaussian_rbf"

python train_test/Load/load_qr_gefcom2014.py 5 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 6 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 7 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 8 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 9 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 10 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 11 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 12 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 13 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 14 "a_laplacian"
python train_test/Load/load_qr_gefcom2014.py 15 "a_laplacian"

python train_test/Load/load_qr_gefcom2014.py 5 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 6 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 7 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 8 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 9 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 10 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 11 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 12 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 13 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 14 "gaussian_rbf"
python train_test/Load/load_qr_gefcom2014.py 15 "gaussian_rbf"